---
stages:
  - validate
  - format

default:
  image:
    name: hashicorp/terraform:1.3.6
    entrypoint: [""]
  before_script:
    - terraform init -backend=false

validate:
  stage: validate
  script:
    - terraform validate

format:
  stage: format
  script:
    - terraform fmt -check -recursive -diff
